FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends `
    git curl && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash student
USER student
WORKDIR /home/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]
